### ISSUE TITLE
 new Google Play In-App Review API not working, popup is not available

### ISSUE THREAD

**Issue by kw2019ltd** [Skyost/RateMyApp#64]
hi 
see below video where rating was request and Review popup not able to show

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/47334522/90228306-a95c3900-de1e-11ea-87cf-b2b3c28b6b7a.gif)

**Comment by Skyost** [comment]
Please fill the issue template. Then make sure you read this two things :

1. "You must upload your app to the Play Store to test the plugin. An easy way to do this is to build an apk/app bundle and upload it via [internal app sharing](https://play.google.com/apps/publish/internalappsharing/)." From [in_app_review](https://pub.dev/packages/in_app_review#android).
2. "To provide a great user experience, Google Play enforces a quota on how often a user can be shown the review dialog. Because of this, calling a `launchReviewFlow` method might not always display a dialog. For example, you should not have a call-to-action option (such as a button) to trigger a review as a user might have already hit their quota and the flow won’t be shown, presenting a broken experience to the user." From the [official documentation](https://developer.android.com/guide/playcore/in-app-review). This means that when you call the `showRateDialog` (or `showRateDialog`) method with `ignoreNative` set to `false`, the Google Play Services may choose to not show the dialog.

**Comment by kw2019ltd** [comment]
Yes i see its now working, Q if user decide not now will the popup
displayed again according to old functionality?

**Comment by Skyost** [comment]
@kw2019ltd You're talking about Google's new rating dialog or Rate my app rating dialog ?

**Comment by kw2019ltd** [comment]
Google dialog.

**Comment by Skyost** [comment]
@kw2019ltd They handle it as they want and the developer cannot do anything. They can decide to show it or not to show it.
